### ISSUE TITLE
Search box crash

### ISSUE THREAD

**Issue by Gilen76** [Slipity/App#31]
whenever i click on the “search”, it crashes. Pls help. Thank you.

**Comment by josiaho** [comment]
Hello! Do you happen to be using an external keyboard? Which device & OS version are you experiencing this on?

**Comment by Gilen76** [comment]
Yes sir

**Comment by Gilen76** [comment]
Im using ipados 18.1 ipad air 2020

**Comment by Gilen76** [comment]
When i touch the “search”, it crashes immediately and it doesn’t give me a chance to type even a single letter.

**Comment by josiaho** [comment]
Thanks for the info. This appears to have been introduced in iOS/ipados 18 and specific to using an external keyboard.

I'll grab a Bluetooth keyboard to do a little testing and see what I can find.

**Comment by josiaho** [comment]
The keyboard issue appears to be an on-going iPadOS 18 bug that creates conflicting layout constraints between the toolbar that appears for Predictive Text and Shortcuts when a hardware keyboard is detected.

A temporary workaround: Disable “Predictive Text” and “Shortcuts” in Settings > General > Keyboards

This will prevent the keyboard toolbar from displaying and creating conflicting constraints. The downside: since this is a system-wide setting, you will no longer be able to access the toolbar within any app.

Hopefully Apple will fix this in a future update. In other apps that I’ve built with SwiftUI I don’t see the same issue - so I’m guessing it has something to do with my custom UIViews in Slipity? A longterm solution might be to rebuild Slipity from scratch in SwiftUI - but yikes, that could take a while.
